version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 50
    commit-message:
      prefix: "chore"
      include: "scope"