server:
  port: 8088

spring:
  mvc:
    view:
      suffix: .html
      prefix: /views/
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB
  datasource:
    url: jdbc:mysql://localhost:3306/chatting?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql

mybatis:
  mapper-locations: classpath:mapper/*
  type-aliases-package: com.sxrekord.chatting.model.po
  configuration:
    map-underscore-to-camel-case: true

file:
  upload:
    location: F:/repo/chatting/UploadFile/
  user:
    avatar:
      location: F:/repo/chatting/avatar/
      default: /avatar/default_user_avatar.jpg


netty:
  server:
    port: 3333

config:
  exclude-uri: [ /login, /admin/** ]
  include-uri: [ /chatroom/** ]