server:
  port: 8088

spring:
  mvc:
    view:
      suffix: .html
      prefix: /views/
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB

file:
 upload:
   path: F:/repo/chatting/UploadFile/

netty:
  server:
    port: 3333

config:
  exclude-uri: [ /login, /admin/** ]
  include-uri: [ /chatroom/** ]