name: Spring Boot CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop
      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          character set server: 'utf8'
          collation server: 'utf8_general_ci'
          mysql version: '8.0'
          mysql database: 'chatting'
          mysql user: 'webchatting'
          mysql password: 'webchatting'
      - name: Set up Redis
        uses: supercharge/redis-github-action@1.5.0
        with:
          redis-image: redis
          redis-version: latest
          redis-port: 6379
          redis-container-name: redis
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: x64
          cache: maven
      - name: Replace service name
        run: bash ./scripts/replace-service-name.sh
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
