name: Build and Push Docker Image

on:
  # Schedule a workflow to run at 4am every Tuesday.
  schedule:
    - cron: '0 4 * * 2'
  workflow_dispatch:

env:
  IMAGE_NAME: sxrekord/chatting:latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build the Docker image
        run: |
          docker build -t $IMAGE_NAME .

      - name: Push the Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}
